# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job: sc
aks:
  image: marorl.azurecr.cn/marorl
  storage_account: maro
  file_share: rltest
scenario_dir: /rltest
scenario: supply_chain
load_policy_dir: "/rltest/checkpoints/sc"
checkpoint_dir: "/rltest/checkpoints/sc"
log_dir: "/rltest/logs/sc"
mode: sync  # single, sync, async
num_episodes: 4
eval_schedule: 2
sync:
  num_rollouts: 3
  num_eval_rollouts: 1
  rollout_type: distributed   # multi-process, distributed
  distributed:
    min_finished_workers: 2
    max_extra_recv_tries: 1
    extra_recv_timeout: 200
async:
  max_lag: 3
  num_rollouts: 3
policy_manager:
  type: distributed   # simple, multi-process, distributed
  distributed:
    num_hosts: 2
redis:
  host: maro
  port: 6379